spring.application.name: ConfigClient
spring.config.import: optional:configserver:http://localhost:8888 # Default port

token.secret: Default secret token

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest