server.port: 8888
spring.application.name: ConfigServer

spring.profiles.active: native  # Native means local filesystem
spring.cloud.config.server.native.search-locations: file:///${user.home}/Documents/Playground/JavaSandbox/spring-config-local

#spring.profiles.active: native, git  # Can use both together
