server.port: 8888
spring.application.name: ConfigServer

spring.cloud.config.server.git:
  clone-on-start: true
  uri: https://github.com/OmnicWolf/spring-shipwreck-config
  username: omnicwolf
  password: <personal-access-token> # If 2FA enabled, else password

management.endpoints.web.exposure.include: busrefresh

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest