server.port: ${DISCOVERY_PORT:8761}
spring.application.name: EurekaDiscoveryServer
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl.defaultZone: http://localhost:${server.port}/eureka