server.port: 8000

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instanceId: localhost:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl.defaultZone: http://localhost:${DISCOVERY_PORT:8761}/eureka

spring:
  application.name: ApiGateway-Server-V0
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true