spring:
  datasource:
    username: sa
    password:
    driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:testdb  #in-memory  # url is required for h2
    #url: jdbc:h2:file:~/pokemonleaguedb     # H2 Console URL=jdbc:h2:~/pokemonleaguedb
    url: jdbc:h2:file:./pokemonleaguedb
  h2.console:
    enabled: true # console is required for h2
    path: /h2-console       # default
    settings:
      trace: false
      web-allow-others: false
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true
      # hibernate.dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect